name: Deploy App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: environment
        required: true

run-name: Deploy ${{ github.event.inputs.environment }} app

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -a "${FLY_APP_NAME}" -t "${FLY_API_TOKEN}" --remote-only --build-arg SENTRY_AUTH_TOKEN="${SENTRY_AUTH_TOKEN}"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME: ${{ vars.FLY_APP_NAME }}
